### ISSUE TITLE
Game crashes (rel 1.4.1)

### ISSUE THREAD

**Issue by Jervi71** [DrBeef/QuakeQuest#21] opened 2019-08-20 22:29 UTC
Hi,
with the latest version (1.4.1) the game often crashes.
I attach screenshot of two crashes.

![com drbeef quakequest-20190820-214236](https://user-images.githubusercontent.com/53384389/63388925-4d490b00-c3aa-11e9-8472-5a47ebd6d789.jpg)
![com drbeef quakequest-20190820-214806](https://user-images.githubusercontent.com/53384389/63388928-520dbf00-c3aa-11e9-970a-64f29f1b1f59.jpg)

**Comment by Saralise** [comment] 2019-08-21 01:59
I believe I'm getting the same crash.  Not far into the second mission. I'll have to load it back up and check if it happens again and get a screen shot.  1.4.1 Latest Quest firmware.

**Comment by DrBeef** [comment] 2019-08-21 07:27
I think I've figured out the cause of the issue.. hopefully I'll get a
chance to test my solution and drop a hot-fix later today.

**Comment by DrBeef** [comment] 2019-08-21 11:30
If you update now it is hopefully fixed, please let me know if you see it again, closing this issue in the meantime

**Closed as completed by DrBeef** 2019-08-21 11:30 UTC

**Comment by Jervi71** [comment] 2019-08-21 23:20
Ok, as soon as I can try it, I tell you 👍
Thanks

**Comment by Jervi71** [comment] 2019-08-22 17:21
I tried three levels. All right! 👍
Great! Thx
